Repository JOY-RIDE/JOYRIDE, pull requests merged in 2022-09, with the labels that each got.

#88 feat : meet api - 모임조회, 모임 세부조회, 모임 생성
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetProvider.java
  src/main/java/com/joyride/ms/src/meet/MeetService.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetCreateReq.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetDetailRes.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetListRes.java
  src/main/java/com/joyride/ms/src/meet/model/Meet.java
  src/main/java/com/joyride/ms/src/user/model/User.java
  src/main/java/com/joyride/ms/src/user/model/UserDetail.java
Labels: backend, feat✨

#89 feat: 모임 만들기 UI
  client/package.json
  client/src/apis/meetupAPI.ts
  client/src/components/common/AuthFormInput/index.tsx
  client/src/components/common/CheckBox/index.tsx
  client/src/components/common/Chip/Chip.module.scss
  client/src/components/common/Chip/index.tsx
  client/src/components/common/DateTimePicker/DateTimePicker.module.scss
  client/src/components/common/DateTimePicker/index.tsx
  client/src/components/common/ErrorMessage/ErrorMessage.module.scss
  client/src/components/common/FilterOptionChip/index.tsx
  client/src/components/common/OptionChip/OptionChip.module.scss
  client/src/components/common/PlusMinusButton/PlusMinusButton.module.scss
  client/src/components/common/PlusMinusButton/index.tsx
  client/src/components/common/SelectButton/SelectButton.module.scss
  client/src/components/common/SelectButton/index.tsx
  client/src/components/common/SelectList/index.tsx
  client/src/components/common/TextArea/index.tsx
  client/src/components/common/TextInput/TextInput.module.scss
  client/src/components/common/TextInput/index.tsx
  client/src/components/meetups/MeetupCreationForm/MeetupCreationForm.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupCreator/MeetupCreator.module.scss
  client/src/components/meetups/MeetupCreator/index.tsx
  client/src/components/meetups/MeetupFilterBoard/MeetupFilterBoard.module.scss
  client/src/components/meetups/MeetupFilterBoardOptions/MeetupFilterBoardOptions.module.scss
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/meetups/MeetupItem/MeetupItem.module.scss
  client/src/components/meetups/MeetupList/MeetupList.module.scss
  client/src/components/signup/SignupBasicForm/SignupBasicForm.module.scss
  client/src/components/signup/SignupDetailForm/SignupDetailForm.module.scss
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/hooks/useResponsivePopup.ts
  client/src/routes/Meetups/Meetups.module.scss
  client/src/styles/base.scss
  client/src/styles/mixins.scss
  client/src/styles/typography.scss
  client/src/types/common.ts
  client/src/types/meetup.ts
  client/src/utils/constants.ts
  client/src/utils/filter.ts
  client/src/utils/getErrorMessage.ts
  client/yarn.lock
Labels: feat✨, frontend

#91 feat: 회원가입 관련 변경
  client/src/apis/authAPI.ts
  client/src/apis/axios.ts
  client/src/assets/images/socialLogin_google.svg
  client/src/assets/images/socialLogin_kakao.svg
  client/src/assets/images/socialLogin_naver.svg
  client/src/components/common/DateTimePicker/index.tsx
  client/src/components/common/FormInputWithErrorMessageWrapper/FormInputWithErrorMessageWrapper.module.scss
  client/src/components/common/FormInputWithErrorMessageWrapper/index.tsx
  client/src/components/common/SelectList/index.tsx
  client/src/components/login/LoginForm/LoginForm.module.scss
  client/src/components/login/LoginForm/index.tsx
  client/src/components/login/SocialLogin/index.tsx
  client/src/components/meetups/MeetupCreationForm/MeetupCreationForm.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/MeetupFilterBoardOptions.module.scss
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/components/signup/SignupBasicForm/SignupBasicForm.module.scss
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupCompleted/index.tsx
  client/src/components/signup/SignupDetailForm/SignupDetailForm.module.scss
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupTermsForm/index.tsx
  client/src/routes/Signup/index.tsx
  client/src/styles/base.scss
  client/src/types/auth.ts
  client/src/types/meetup.ts
  client/src/utils/constants.ts
  client/src/utils/filter.ts
  client/src/utils/getErrorMessage.ts
  client/src/utils/regex.ts
Labels: feat✨, frontend

#95 refactor: old 변수 이름 birthYear로 변경
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSignupReq.java
  src/main/java/com/joyride/ms/src/user/UserController.java
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/dto/GetUserRes.java
  src/main/java/com/joyride/ms/src/user/dto/PatchUserReq.java
  src/main/java/com/joyride/ms/src/user/model/User.java
Labels: backend, refactor💫

#96 Feature/코스 리뷰 필터링 api/#94
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseRes.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseReviewRes.java
  src/main/java/com/joyride/ms/src/course/model/GetFilteringReviewRes.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewReq.java
Labels: backend, feat✨

#99 유저api 수정 및 accessToken 만료시간 변경
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/AuthService.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAccessRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAutoSigninRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSigninRes.java
  src/main/java/com/joyride/ms/src/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/joyride/ms/src/user/UserController.java
Labels: backend, refactor💫

#100 feat: 코스 디테일 UI
  client/package.json
  client/public/icons/pedal_bike_icon.svg
  client/public/icons/restaurant_icon.svg
  client/public/icons/spanner_icon.svg
  client/public/icons/wc_icon.svg
  client/public/index.html
  client/src/App.tsx
  client/src/apis/CrsAPI.ts
  client/src/components/common/Like/Like.module.scss
  client/src/components/common/Like/index.tsx
  client/src/components/common/PageTitle/PageTitle.module.scss
  client/src/components/common/Paging/Paging.module.scss
  client/src/components/common/Paging/index.tsx
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/road/CrsDesc/index.tsx
  client/src/components/road/CrsInfo/CrsInfo.module.scss
  client/src/components/road/CrsInfo/index.tsx
  client/src/components/road/MapCheckOption/MapCheckOption.module.scss
  client/src/components/road/MapCheckOption/index.tsx
  client/src/components/road/MapDetail/MapDetail.module.scss
  client/src/components/road/MapDetail/index.tsx
  client/src/components/road/MapOverview/MapOverview.module.scss
  client/src/components/road/MapOverview/index.tsx
  client/src/components/road/ReviewFilter/ReviewFilter.module.scss
  client/src/components/road/ReviewFilter/index.tsx
  client/src/components/road/ReviewFilterOptions/ReviewFilterOptions.module.scss
  client/src/components/road/ReviewFilterOptions/index.tsx
  client/src/components/road/ReviewForm/ReviewForm.module.scss
  client/src/components/road/ReviewForm/index.tsx
  client/src/components/road/ReviewItem/ReviewItem.module.scss
  client/src/components/road/ReviewItem/index.tsx
  client/src/components/road/ReviewTitle/ReviewTitle.module.scss
  client/src/components/road/ReviewTitle/index.tsx
  client/src/components/road/ReviewWriter/ReviewWriter.module.scss
  client/src/components/road/ReviewWriter/index.tsx
  client/src/components/roads/CourseFilterBoard/CourseFilterBoard.module.scss
  client/src/components/roads/CourseFilterBoard/index.tsx
  client/src/components/roads/CourseFilterBoardOptions/CourseFilterBoardOptions.module.scss
  client/src/components/roads/CourseFilterBoardOptions/index.tsx
  client/src/components/roads/CourseFilterChoices/CourseFilterChoices.module.scss
  client/src/components/roads/CourseFilterChoices/index.tsx
  client/src/components/roads/CourseFilterToggleButton/CourseFilterToggleButton.module.scss
  client/src/components/roads/CourseFilterToggleButton/index.tsx
  client/src/components/roads/SortBox/index.tsx
  client/src/components/roads/SortItem/index.tsx
  client/src/hooks/useClientFilter.ts
  client/src/routes/Road/Road.module.scss
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/Roads.module.scss
  client/src/routes/Roads/index.tsx
  client/src/states/common.ts
  client/src/states/course.ts
  client/src/types/course.ts
  client/src/utils/constants.ts
  client/src/utils/filter.ts
  client/src/utils/getErrorMessage.ts
  client/src/utils/stringify.ts
  client/yarn.lock
Labels: feat✨, frontend

#106 Feature/#103
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSignupReq.java
  src/main/java/com/joyride/ms/src/s3/AwsS3Service.java
  src/main/java/com/joyride/ms/src/user/UserController.java
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/UserProvider.java
  src/main/java/com/joyride/ms/src/user/UserService.java
  src/main/java/com/joyride/ms/src/user/dto/PatchUserReq.java
  src/main/java/com/joyride/ms/src/user/dto/UserPasswordReq.java
  src/main/java/com/joyride/ms/util/BaseResponse.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
Labels: backend, refactor💫, feat✨

#111 모임 참여 api 구현
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetProvider.java
  src/main/java/com/joyride/ms/src/meet/MeetService.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
Labels: backend, refactor💫, feat✨

#114 feat: 로그인/silent refresh 에러 핸들링 로직 추가
  client/src/apis/authAPI.ts
  client/src/apis/userAPI.ts
  client/src/components/login/LoginForm/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/index.tsx
Labels: feat✨, frontend

#116 feat: 모임 집결지 필드 추가 & design: MeetupPathMap
  client/src/apis/authAPI.ts
  client/src/apis/meetupAPI.ts
  client/src/assets/icons/completed.svg
  client/src/assets/icons/meetup_gatheringPlace.svg
  client/src/assets/icons/meetup_stop.svg
  client/src/components/meetup/MeetupPathMap/MeetupPathMap.module.scss
  client/src/components/meetup/MeetupPathMap/index.tsx
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupSummary/index.tsx
  client/src/routes/Meetup/index.tsx
  client/src/types/meetup.ts
  client/src/utils/getErrorMessage.ts
Labels: feat✨, frontend

#115 feat: 모임 탈퇴 및 삭제 api 구현
  src/main/java/com/joyride/ms/src/auth/dto/PostSignupReq.java
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetProvider.java
  src/main/java/com/joyride/ms/src/meet/MeetService.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetCreateReq.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetDetailRes.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetListRes.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
Labels: backend, feat✨

#119 모임 생성 기본이미지 설정 및 모임 조회시 path구분자 수정
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
Labels: backend, refactor💫

#121 feat: Meetup 리스트/디테일/생성/참가 기능
  client/src/App.tsx
  client/src/apis/meetupAPI.ts
  client/src/components/common/ContentToggleButton/ContentToggleButton.module.scss
  client/src/components/common/ErrorMessage/ErrorMessage.module.scss
  client/src/components/common/Toast/Toast.module.scss
  client/src/components/login/LoginForm/LoginForm.module.scss
  client/src/components/login/LoginForm/index.tsx
  client/src/components/meetup/MeetupJoinBar/MeetupJoinBar.module.scss
  client/src/components/meetup/MeetupJoinBar/index.tsx
  client/src/components/meetup/MeetupPathMap/index.tsx
  client/src/components/meetup/MeetupRoute/MeetupRoute.module.scss
  client/src/components/meetups/MeetupCreationForm/MeetupCreationForm.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupCreator/index.tsx
  client/src/components/meetups/MeetupItem/index.tsx
  client/src/components/meetups/MeetupList/index.tsx
  client/src/components/meetups/MeetupSummary/index.tsx
  client/src/components/signup/SignupBasicForm/SignupBasicForm.module.scss
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/index.tsx
  client/src/routes/AuthPage/FindEmail/FindEmail.module.scss
  client/src/routes/AuthPage/FindEmail/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/Meetups.module.scss
  client/src/routes/Meetups/index.tsx
  client/src/states/auth.ts
  client/src/types/meetup.ts
  client/src/utils/order.ts
Labels: feat✨, frontend

#123 feat: 정원 초과 error 추가 및 gatheringPlace 추가
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetProvider.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetDetailRes.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetListRes.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
Labels: backend, feat✨

#125 feat: 모임 디테일 댓글 제외 완성, Modal 구현
  client/package.json
  client/src/App.tsx
  client/src/apis/meetupAPI.ts
  client/src/components/common/AskLogin/AskLogin.module.scss
  client/src/components/common/AskLogin/index.tsx
  client/src/components/common/Button/index.tsx
  client/src/components/common/FilterOptionChip/index.tsx
  client/src/components/common/Modal/index.tsx
  client/src/components/meetup/AskMeetupJoin/AskMeetupJoin.module.scss
  client/src/components/meetup/AskMeetupJoin/index.tsx
  client/src/components/meetup/MeetupJoinBar/MeetupJoinBar.module.scss
  client/src/components/meetup/MeetupJoinBar/index.tsx
  client/src/components/meetup/MeetupParticipantList/MeetupParticipantList.module.scss
  client/src/components/meetup/MeetupParticipantList/index.tsx
  client/src/components/meetups/MeetupCreator/index.tsx
  client/src/components/meetups/MeetupFilterBoard/MeetupFilterBoard.module.scss
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/hooks/useDialog.ts
  client/src/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/index.tsx
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/index.tsx
  client/src/states/common.ts
  client/src/types/meetup.ts
  client/yarn.lock
Labels: feat✨, frontend

#129 feat: 코스 필터링, 서버 연결 제외한 기능
  client/public/icons/pedal_bike_marker.svg
  client/public/icons/restaurant_marker.svg
  client/public/icons/spanner_marker.svg
  client/public/icons/wc_marker.svg
  client/public/index.html
  client/src/apis/CrsAPI.ts
  client/src/components/common/Like/index.tsx
  client/src/components/common/Paging/index.tsx
  client/src/components/road/CrsDesc/index.tsx
  client/src/components/road/MapCheckOption/MapCheckOption.module.scss
  client/src/components/road/MapCheckOption/index.tsx
  client/src/components/road/MapDetail/MapDetail.module.scss
  client/src/components/road/MapDetail/index.tsx
  client/src/components/road/ReviewForm/index.tsx
  client/src/components/road/ReviewWriter/index.tsx
  client/src/components/roads/CourseFilterBoard/index.tsx
  client/src/components/roads/CourseFilterChoices/index.tsx
  client/src/components/roads/CourseFilterToggleButton/index.tsx
  client/src/components/roads/CourseItem/CourseItem.module.scss
  client/src/components/roads/CourseItem/index.tsx
  client/src/components/roads/CourseList/CourseList.module.scss
  client/src/components/roads/CourseList/index.tsx
  client/src/components/roads/OrderItem/OrderItem.module.scss
  client/src/components/roads/OrderItem/index.tsx
  client/src/components/roads/OrderList/OrderList.module.scss
  client/src/components/roads/OrderList/index.tsx
  client/src/components/roads/SortBox/SortBox.module.scss
  client/src/components/roads/SortBox/index.tsx
  client/src/components/roads/SortItem/SortItem.module.scss
  client/src/components/roads/SortItem/index.tsx
  client/src/hooks/useClientFilter.ts
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/Roads.module.scss
  client/src/routes/Roads/index.tsx
  client/src/states/course.ts
  client/src/types/course.ts
  client/src/utils/constants.ts
  client/src/utils/filter.ts
  client/src/utils/getErrorMessage.ts
  client/src/utils/order.ts
  client/yarn.lock
Labels: feat✨, frontend

#130 feat: 모임 만들기 완성
  client/src/apis/axios.ts
  client/src/apis/meetupAPI.ts
  client/src/assets/icons/meetup_gatheringPlace.svg
  client/src/assets/icons/meetup_stop.svg
  client/src/components/common/AskLogin/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/meetup/MeetupJoinBar/index.tsx
  client/src/components/meetup/MeetupPathMap/index.tsx
  client/src/components/meetup/MeetupRoute/MeetupRoute.module.scss
  client/src/components/meetup/MeetupRoute/index.tsx
  client/src/components/meetups/MeetupCreationForm/MeetupCreationForm.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupCreator/index.tsx
  client/src/components/meetups/MeetupFilterBoard/index.tsx
  client/src/components/resetPassword/PasswordResetForm/index.tsx
  client/src/components/road/ReviewForm/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupTermsForm/index.tsx
  client/src/routes/AuthPage/FindEmail/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/index.tsx
  client/src/routes/Roads/index.tsx
  client/src/types/meetup.ts
  client/src/utils/getErrorMessage.ts
  yarn.lock
Labels: feat✨, frontend

#135 Request/#122
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetProvider.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetFilterReq.java
Labels: backend, feat✨, request🙏

#134 feat: 모임 페이지네이션/모임 참가 리팩토링/메인 페이지 모임 섹션
  client/src/components/home/MeetUp/index.tsx
  client/src/components/home/MeetupItem/MeetupItem.module.scss
  client/src/components/home/MeetupItem/index.tsx
  client/src/components/home/MeetupList/MeetupList.module.scss
  client/src/components/home/MeetupList/index.tsx
  client/src/components/layout/Footer/index.tsx
  client/src/components/layout/Header/index.tsx
  client/src/components/meetup/MeetupJoinBar/MeetupJoinBar.module.scss
  client/src/components/meetup/MeetupJoinBar/index.tsx
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupCreator/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/main.scss
  client/src/routes/AuthPage/FindEmail/FindEmail.module.scss
  client/src/routes/Home/Home.module.scss
  client/src/routes/Home/index.tsx
  client/src/routes/Layout/Layout.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/index.tsx
  client/src/styles/base.scss
  client/src/styles/mixins.scss
  client/src/types/meetup.ts
Labels: refactor💫, feat✨, frontend

#139 Feature/코스 리스트에 이미지 추가/#138
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/CourseInfo.java
  src/main/java/com/joyride/ms/src/course/model/CourseReview.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseLikeReq.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseListRes.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseNameListRes.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseRes.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseReviewRes.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewRes.java
Labels: backend, refactor💫

#141 feat: 모임 리스트 페이지네이션/필터 API 연결/모임 관련 부분 보완
  client/src/apis/authAPI.ts
  client/src/apis/meetupAPI.ts
  client/src/components/common/DateTimePicker/index.tsx
  client/src/components/common/Modal/index.tsx
  client/src/components/common/NoResults/NoResults.module.scss
  client/src/components/common/NoResults/index.tsx
  client/src/components/home/MeetupItem/MeetupItem.module.scss
  client/src/components/home/MeetupItem/index.tsx
  client/src/components/home/MeetupList/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/meetup/MeetupJoinBar/index.tsx
  client/src/components/meetup/MeetupRoute/MeetupRoute.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupFilterBoard/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/components/meetups/Pagination/Pagination.module.scss
  client/src/components/meetups/Pagination/index.tsx
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/routes/Home/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/index.tsx
Labels: feat✨, frontend

#140 feat: 코스 디테일 기능
  client/src/App.tsx
  client/src/apis/courseAPI.ts
  client/src/apis/coursesAPI.ts
  client/src/apis/meetupAPI.ts
  client/src/components/common/Like/index.tsx
  client/src/components/road/CrsInfo/index.tsx
  client/src/components/road/MapDetail/index.tsx
  client/src/components/road/MapOverview/index.tsx
  client/src/components/road/ReviewFilter/ReviewFilter.module.scss
  client/src/components/road/ReviewFilter/index.tsx
  client/src/components/road/ReviewFilterOptions/index.tsx
  client/src/components/road/ReviewForm/index.tsx
  client/src/components/road/ReviewItem/ReviewItem.module.scss
  client/src/components/road/ReviewItem/index.tsx
  client/src/components/road/ReviewWriter/index.tsx
  client/src/components/roads/CourseFilterBoardOptions/index.tsx
  client/src/components/roads/CourseItem/index.tsx
  client/src/components/roads/CourseList/CourseList.module.scss
  client/src/components/roads/CourseList/index.tsx
  client/src/routes/Road/Road.module.scss
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/index.tsx
  client/src/types/course.ts
  client/src/utils/constants.ts
  client/src/utils/order.ts
  client/src/utils/stringify.ts
Labels: feat✨, frontend

#144 feat: 메인페이지 코스 UI
  client/src/components/home/CourseItem/CourseItem.module.scss
  client/src/components/home/CourseItem/index.tsx
  client/src/components/home/CourseList/CourseList.module.scss
  client/src/components/home/CourseList/index.tsx
  client/src/components/road/MapOverview/index.tsx
  client/src/routes/Home/index.tsx
  client/src/routes/Roads/index.tsx
Labels: feat✨, frontend

#150 feat: 마이페이지 레이아웃/프로필 보기
  client/src/App.tsx
  client/src/apis/axios.ts
  client/src/apis/meetupAPI.ts
  client/src/components/Mypage/BookmarkedMeetupsPreview/index.tsx
  client/src/components/Mypage/JoinedMeetupsPreview/index.tsx
  client/src/components/Mypage/MeetupItem/MeetupItem.module.scss
  client/src/components/Mypage/MeetupItem/index.tsx
  client/src/components/Mypage/MeetupList/MeetupList.module.scss
  client/src/components/Mypage/MeetupList/index.tsx
  client/src/components/Mypage/MyMeetupsPreview/MyMeetupsPreview.module.scss
  client/src/components/Mypage/MyMeetupsPreview/index.tsx
  client/src/components/Mypage/Profile/Profile.module.scss
  client/src/components/Mypage/Profile/index.tsx
  client/src/components/Mypage/SectionTitle/SectionTitle.module.scss
  client/src/components/Mypage/SectionTitle/index.tsx
  client/src/components/common/NoResults/index.tsx
  client/src/components/common/PageTitle/PageTitle.module.scss
  client/src/components/home/MeetupItem/MeetupItem.module.scss
  client/src/components/home/MeetupItem/index.tsx
  client/src/components/layout/Header/Header.module.scss
  client/src/components/layout/Header/index.tsx
  client/src/components/meetup/MeetupRoute/MeetupRoute.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupRoutePreview/index.tsx
  client/src/components/meetups/MeetupSummary/index.tsx
  client/src/routes/AuthPage/FindEmail/index.tsx
  client/src/routes/Home/Home.module.scss
  client/src/routes/Home/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Meetups/index.tsx
  client/src/routes/Mypage/BookmarkedMeetups/index.tsx
  client/src/routes/Mypage/JoinedMeetups/index.tsx
  client/src/routes/Mypage/MyMeetups/index.tsx
  client/src/routes/Mypage/Mypage.module.scss
  client/src/routes/Mypage/index.tsx
  client/src/utils/order.ts
Labels: feat✨, frontend

#148 refactor: 좋아요 생성 시 좋아요 id를 리턴하도록 코드 수정(#147)
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseLikeRes.java
Labels: backend, refactor💫

#151 feat: 좋아요한 코스 리스트 조회 api 개발(#149)
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseListRes.java
Labels: backend, feat✨

#157 fix: config설정
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  yarn.lock
Labels: backend, feat✨

#158 fix: cors 설정
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
Labels: backend, feat✨

#160 refactor: 좋아요 조회&삭제 api 수정(#159)
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
Labels: backend, refactor💫

#162 test
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
Labels: bug🐞, backend, feat✨

#163 refactor: 필터링 api 자전거 길만 나오도록 수정(#161)
  src/main/java/com/joyride/ms/src/course/CallApi.java
Labels: backend, refactor💫

#164 feat: 유저 정보 수정 UI
  client/src/components/layout/Header/index.tsx
  client/src/components/mypage/ModifierForm/ModifierForm.module.scss
  client/src/components/mypage/ModifierForm/index.tsx
  client/src/routes/Mypage/ModifyProfile/ModifyProfile.module.scss
  client/src/routes/Mypage/ModifyProfile/index.tsx
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/Roads.module.scss
  client/src/routes/Roads/index.tsx
  client/src/types/auth.ts
  client/src/utils/constants.ts
  client/src/utils/getErrorMessage.ts
Labels: frontend

#166 feat: 좋아요 취소
  client/src/components/common/Like/index.tsx
  client/src/components/home/CourseList/index.tsx
  client/src/components/mypage/ModifierForm/index.tsx
  client/src/components/road/MapOverview/index.tsx
  client/src/routes/Roads/index.tsx
Labels: feat✨, frontend

#168 Request/#137
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetProvider.java
  src/main/java/com/joyride/ms/src/meet/MeetService.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
Labels: backend, feat✨, request🙏

#171 feat: meet 조회 최신순 정렬
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
Labels: bug🐞, backend

#169 design: 라이딩 실력/모임 코스맵 설명
  client/src/App.tsx
  client/src/apis/meetupAPI.ts
  client/src/components/common/RidingSkills/RidingSkills.module.scss
  client/src/components/common/RidingSkills/index.tsx
  client/src/components/layout/Footer/Footer.module.scss
  client/src/components/layout/Header/Header.module.scss
  client/src/components/login/SocialLogin/SocialLogin.module.scss
  client/src/components/login/SocialLoginButton/SocialLoginButton.module.scss
  client/src/components/meetup/MeetupJoinBar/MeetupJoinBar.module.scss
  client/src/components/meetup/MeetupParticipantList/MeetupParticipantList.module.scss
  client/src/components/meetup/MeetupPathMap/index.tsx
  client/src/components/meetup/MeetupPathMapGuide/MeetupPathMap.module.scss
  client/src/components/meetup/MeetupPathMapGuide/index.tsx
  client/src/components/meetup/MeetupRoute/MeetupRoute.module.scss
  client/src/components/meetups/MeetupCreationForm/MeetupCreationForm.module.scss
  client/src/components/meetups/MeetupCreationForm/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/MeetupFilterBoardOptions.module.scss
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupDetailForm/SignupDetailForm.module.scss
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/routes/Home/Home.module.scss
  client/src/routes/Home/index.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/types/auth.ts
  client/src/utils/getErrorMessage.ts
  client/src/utils/regex.ts
Labels: feat✨, frontend

#175 bug: 나이 필터 오류
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
Labels: bug🐞, backend

#176 Request/#173
  src/main/java/com/joyride/ms/src/meet/MeetController.java
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/MeetService.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetCommentCreateReq.java
Labels: backend, feat✨, request🙏

#177 feat: 유저 프로필 사진 수정, 통합검색
  client/src/App.tsx
  client/src/apis/meetupAPI.ts
  client/src/components/layout/Header/Header.module.scss
  client/src/components/layout/Header/index.tsx
  client/src/components/mypage/ModifierForm/index.tsx
  client/src/components/search/SearchedCourseItem/SearchedCourseItem.module.scss
  client/src/components/search/SearchedCourseItem/index.tsx
  client/src/components/search/SearchedMeetupItem/SearchedMeetupItem.module.scss
  client/src/components/search/SearchedMeetupItem/SearchedMeetupItem.tsx
  client/src/routes/Auth/DeleteAccount/DeleteAccount.module.scss
  client/src/routes/Auth/DeleteAccount/index.tsx
  client/src/routes/Mypage/ModifyProfile/index.tsx
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/index.tsx
  client/src/routes/Search/Search.module.scss
  client/src/routes/Search/index.tsx
Labels: feat✨, frontend

#179 refactor: 유저 프로필 수정 api dto 수정
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/dto/PatchUserReq.java
Labels: backend, refactor💫

#181 refactor: 모임 세부조회시 댓글 조회
  src/main/java/com/joyride/ms/src/meet/model/CommentInfo.java
Labels: backend, refactor💫, feat✨

#182 feat: 모임 댓글 마크업 & chore: proxy 설정 변경
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/apis/courseAPI.ts
  client/src/apis/meetupAPI.ts
  client/src/components/meetup/MeetupCommentCreationForm/MeetupCommentCreationForm.module.scss
  client/src/components/meetup/MeetupCommentCreationForm/index.tsx
  client/src/components/meetup/MeetupCommentList/MeetupCommentList.module.scss
  client/src/components/meetup/MeetupCommentList/index.tsx
  client/src/components/meetup/MeetupJoinBar/index.tsx
  client/src/components/mypage/BookmarkedMeetupItem/index.tsx
  client/src/components/mypage/LikedCourseItem/index.tsx
  client/src/components/mypage/Profile/index.tsx
  client/src/routes/Meetup/index.tsx
Labels: feat✨, frontend

#183 feat: 유저 정보 수정
  client/package.json
  client/src/components/layout/Header/Header.module.scss
  client/src/components/layout/Header/index.tsx
  client/src/components/login/SocialLogin/index.tsx
  client/src/components/mypage/ModifierForm/index.tsx
  client/src/hooks/useRecoilCacheRefresh.ts
  client/src/routes/Search/Search.module.scss
  client/src/routes/Search/index.tsx
  client/src/utils/getErrorMessage.ts
  client/yarn.lock
Labels: feat✨, frontend

#186 feat: 코스 관련 모임
  client/src/components/common/Button/Button.module.scss
  client/src/components/common/Button/index.tsx
  client/src/components/road/RelatedMeetups/RelatedMeetups.module.scss
  client/src/components/road/RelatedMeetups/index.tsx
  client/src/components/road/ReviewWriter/ReviewWriter.module.scss
  client/src/components/road/ReviewWriter/index.tsx
  client/src/routes/Road/Road.module.scss
  client/src/routes/Road/index.tsx
Labels: feat✨, frontend

#187 feat: 모임 댓글 삭제
  client/src/apis/meetupAPI.ts
  client/src/components/common/AskLogin/index.tsx
  client/src/components/meetup/MeetupCommentList/MeetupCommentList.module.scss
  client/src/components/meetup/MeetupCommentList/index.tsx
  client/src/components/mypage/Profile/index.tsx
  client/src/components/search/SearchedMeetupItem/SearchedMeetupItem.tsx
  client/src/routes/Meetup/Meetup.module.scss
  client/src/routes/Meetup/index.tsx
  client/src/routes/Search/index.tsx
  client/src/states/auth.ts
Labels: feat✨, frontend

#188 Refactor/#180
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/dto/MeetDetailRes.java
  src/main/java/com/joyride/ms/src/meet/model/CommentInfo.java
Labels: backend, feat✨

#189 hotfix: 모임 세부조회시 댓글 닉네임 이미지 추가
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
  src/main/java/com/joyride/ms/src/meet/model/CommentInfo.java
Labels: bug🐞, backend

#192 hotfix: 프로필 수정 api
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/dto/PatchUserReq.java
Labels: bug🐞, backend

#193 hotfix: 프로필 수정 버튼 주석 제거
  client/src/components/mypage/Profile/index.tsx
Labels: bug🐞, frontend

#194 hotfix: 유저 정보 수정 완료메세지
  client/src/apis/coursesAPI.ts
  client/src/components/mypage/ModifierForm/index.tsx
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/index.tsx
Labels: hotfix🔥

#195 hotfix: 모임 참여 2033에러 수정
  src/main/java/com/joyride/ms/src/meet/MeetDao.java
Labels: bug🐞, backend
