Repository JOY-RIDE/JOYRIDE, pull requests merged in 2022-08, with the labels that each got.

#11 feat: signin & signup api
  .gitignore
  build.gradle
  client/package.json
  client/yarn.lock
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/joyride/ms/JoyrideServerApplication.java
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/AuthDao.java
  src/main/java/com/joyride/ms/src/auth/AuthProvider.java
  src/main/java/com/joyride/ms/src/auth/AuthService.java
  src/main/java/com/joyride/ms/src/auth/PrincipalDetailsService.java
  src/main/java/com/joyride/ms/src/auth/PrincipalOAuth2UserService.java
  src/main/java/com/joyride/ms/src/auth/dto/GetOauth2SuccessRes.java
  src/main/java/com/joyride/ms/src/auth/dto/GetOauth2UserRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAccessReq.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAccessRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAutoSigninReq.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAutoSigninRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSigninReq.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSigninRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSignupOauth2Req.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSignupReq.java
  src/main/java/com/joyride/ms/src/auth/model/PrincipalDetails.java
  src/main/java/com/joyride/ms/src/auth/model/Token.java
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/config/SwaggerConfig.java
  src/main/java/com/joyride/ms/src/jwt/JwtTokenProvider.java
  src/main/java/com/joyride/ms/src/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/com/joyride/ms/src/jwt/handler/CustomAccessDeniedHandler.java
  src/main/java/com/joyride/ms/src/jwt/handler/CustomAuthenticationEntryPointHandler.java
  src/main/java/com/joyride/ms/src/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/UserProvider.java
  src/main/java/com/joyride/ms/src/user/UserService.java
  src/main/java/com/joyride/ms/src/user/model/User.java
  src/main/java/com/joyride/ms/util/BaseException.java
  src/main/java/com/joyride/ms/util/BaseResponse.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
  src/main/resources/application.yml
  src/test/java/com/joyride/ms/JoyrideServerApplicationTests.java
Labels: backend, feat✨

#7 feat: 회원가입 UI
  client/src/App.tsx
  client/src/assets/images/completed.svg
  client/src/components/common/Button/Button.module.scss
  client/src/components/common/Button/index.tsx
  client/src/components/common/CheckBox/index.tsx
  client/src/components/common/ErrorMessage/ErrorMessage.module.scss
  client/src/components/common/ErrorMessage/index.tsx
  client/src/components/common/FormInput/FormInput.module.scss
  client/src/components/common/FormInput/index.tsx
  client/src/components/common/FormInputWrapper/FormInputWrapper.module.scss
  client/src/components/common/FormInputWrapper/index.tsx
  client/src/components/common/PageTitle/PageTitle.module.scss
  client/src/components/common/PageTitle/index.tsx
  client/src/components/common/SelectButton/SelectButton.module.scss
  client/src/components/common/SelectButton/index.tsx
  client/src/components/common/SelectList/index.tsx
  client/src/components/common/TextInput/index.tsx
  client/src/components/common/Toast/index.tsx
  client/src/components/layout/Footer/index.tsx
  client/src/components/login/LoginForm/LoginForm.module.scss
  client/src/components/login/LoginForm/index.tsx
  client/src/components/login/SocialLogin/SocialLogin.module.scss
  client/src/components/login/SocialLogin/index.tsx
  client/src/components/login/SocialLoginButton/SocialLoginButton.module.scss
  client/src/components/login/SocialLoginButton/index.tsx
  client/src/components/signup/FirstSignupForm/FirstSignupForm.module.scss
  client/src/components/signup/FirstSignupForm/index.tsx
  client/src/components/signup/SecondSignupForm/SecondSignupForm.module.scss
  client/src/components/signup/SecondSignupForm/index.tsx
  client/src/components/signup/SignupCompleted/SignupCompleted.module.scss
  client/src/components/signup/SignupCompleted/index.tsx
  client/src/components/signup/SignupFormController/SignupFormController.module.scss
  client/src/components/signup/SignupFormController/index.tsx
  client/src/routes/Layout/Layout.module.scss
  client/src/routes/Layout/index.tsx
  client/src/routes/Login/Login.module.scss
  client/src/routes/Login/index.tsx
  client/src/routes/Signup/Signup.module.scss
  client/src/routes/Signup/index.tsx
  client/src/styles/base.scss
  client/src/styles/mixins.scss
  client/src/styles/variables.scss
Labels: feat✨, frontend

#14 bug: signin/auto & jwt error
  src/main/java/com/joyride/ms/src/auth/dto/PostAccessReq.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAutoSigninReq.java
  src/main/java/com/joyride/ms/src/jwt/JwtTokenProvider.java
Labels: bug🐞, backend

#16 feat: check_email_nickname
  src/main/java/com/joyride/ms/src/auth/AuthController.java
Labels: backend, feat✨

#17 feat: 코스 리스트 UI
  client/package.json
  client/src/api.ts
  client/src/components/common/Loading/Loading.module.scss
  client/src/components/common/Loading/index.tsx
  client/src/components/common/PageTitle/PageTitle.module.scss
  client/src/components/home/MeetUp/index.tsx
  client/src/routes/Home/Home.module.scss
  client/src/routes/Home/index.tsx
  client/src/routes/Road/Road.module.scss
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/Roads.module.scss
  client/src/routes/Roads/index.tsx
Labels: frontend

#18 feat: 회원가입 기능
  README.md
  client/package.json
  client/src/App.tsx
  client/src/apis/AuthAPI.ts
  client/src/apis/axios.ts
  client/src/components/common/ErrorMessage/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/signup/FirstSignupForm/index.tsx
  client/src/components/signup/SecondSignupForm/index.tsx
  client/src/components/signup/SignupTerms/SignupTerms.module.scss
  client/src/components/signup/SignupTerms/index.tsx
  client/src/hooks/useCheckBox.ts
  client/src/hooks/useInput.ts
  client/src/routes/Signup/index.tsx
  client/src/states/atoms.ts
  client/src/styles/base.scss
  client/src/utils/constants.ts
  client/yarn.lock
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: feat✨, frontend

#25 feat: jwt_token_cookie
  client/package-lock.json
  client/package.json
  client/yarn.lock
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/AuthService.java
  src/main/java/com/joyride/ms/src/auth/PrincipalOAuth2UserService.java
  src/main/java/com/joyride/ms/src/auth/dto/GetOauth2SuccessRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAccessRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostAutoSigninRes.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSigninRes.java
  src/main/java/com/joyride/ms/src/jwt/JwtTokenProvider.java
  src/main/java/com/joyride/ms/src/jwt/handler/OAuth2SuccessHandler.java
Labels: backend, feat✨

#27 bug: 자동로그인 & 소셜로그인 jwt 재발급시 쿠키에러
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/jwt/handler/OAuth2SuccessHandler.java
Labels: bug🐞, backend

#30 feat: 프론트엔드 구글 로그인
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/AuthAPI.ts
  client/src/components/common/AuthRoute/index.tsx
  client/src/components/common/PublicRoute copy/index.tsx
  client/src/components/login/SocialLogin/index.tsx
  client/src/components/login/SocialLoginButton/index.tsx
  client/yarn.lock
  src/main/java/com/joyride/ms/src/auth/PrincipalOAuth2UserService.java
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/jwt/handler/OAuth2SuccessHandler.java
Labels: feat✨, frontend

#31 feat: social_signup_signin
  src/main/java/com/joyride/ms/JoyrideServerApplication.java
  src/main/java/com/joyride/ms/src/auth/PrincipalOAuth2UserService.java
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/jwt/handler/OAuth2SuccessHandler.java
  src/main/java/com/joyride/ms/src/user/UserService.java
Labels: backend, feat✨

#33 feat: 로그인 기능
  client/src/App.tsx
  client/src/apis/AuthAPI.ts
  client/src/components/common/PublicRoute/index.tsx
  client/src/components/layout/Header/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/login/SocialLogin/index.tsx
  client/src/components/login/SocialLoginButton/index.tsx
Labels: feat✨, frontend

#37 refactor: 회원가입/로그인
  client/package.json
  client/src/App.tsx
  client/src/apis/AuthAPI.ts
  client/src/apis/authAPI.ts
  client/src/apis/axios.ts
  client/src/components/common/AuthRoute/index.tsx
  client/src/components/common/FormInputWithErrorMessageWrapper/FormInputWithErrorMessageWrapper.module.scss
  client/src/components/common/FormInputWithErrorMessageWrapper/index.tsx
  client/src/components/common/FormInputWrapper/index.tsx
  client/src/components/common/PageTitle/PageTitle.module.scss
  client/src/components/common/PageTitle/index.tsx
  client/src/components/common/PublicRoute/index.tsx
  client/src/components/common/Toast/index.tsx
  client/src/components/layout/Footer/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/signup/FirstSignupForm/index.tsx
  client/src/components/signup/SignupBasicForm/SignupBasicForm.module.scss
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupCompleted/index.tsx
  client/src/components/signup/SignupDetailForm/SignupDetailForm.module.scss
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupFormController/index.tsx
  client/src/components/signup/SignupForms/SignupForms.module.scss
  client/src/components/signup/SignupForms/index.tsx
  client/src/components/signup/SignupTerms/index.tsx
  client/src/components/signup/SignupTerms/terms.ts
  client/src/routes/Signup/index.tsx
  client/src/states/atoms.ts
  client/src/states/selectors.ts
  client/src/typescript/interfaces.ts
  client/src/utils/constants.ts
  client/src/utils/getErrorMessage.ts
  client/yarn.lock
Labels: refactor💫, frontend

#43 feat: 회원가입 약관 동의 UI
  client/package.json
  client/src/components/common/AuthFormInput/AuthFormInput.module.scss
  client/src/components/common/AuthFormInput/index.tsx
  client/src/components/common/AuthFormInputWithErrorMessageWrapper/AuthFormInputWithErrorMessageWrapper.module.scss
  client/src/components/common/AuthFormInputWithErrorMessageWrapper/index.tsx
  client/src/components/common/CheckBox/index.tsx
  client/src/components/common/FormInput/index.tsx
  client/src/components/common/FormInputWithErrorMessageWrapper/index.tsx
  client/src/components/common/TextArea/TextArea.module.scss
  client/src/components/common/TextArea/index.tsx
  client/src/components/login/LoginForm/LoginForm.module.scss
  client/src/components/login/LoginForm/index.tsx
  client/src/components/meetups/MeetupCardContainer/MeetupCardContainer.module.scss
  client/src/components/meetups/MeetupCardContainer/index.tsx
  client/src/components/signup/SignupBasicForm/SignupBasicForm.module.scss
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupDetailForm/SignupDetailForm.module.scss
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupTerms/SignupTerms.module.scss
  client/src/components/signup/SignupTerms/index.tsx
  client/src/routes/Meetups/Meetups.module.scss
  client/src/routes/Meetups/index.tsx
  client/yarn.lock
Labels: feat✨, frontend

#44 feat: 코스 레이아웃
  .gitignore
  client/package.json
  client/src/apis/CrsAPI.ts
  client/src/components/common/Button/Button.module.scss
  client/src/components/common/Button/index.tsx
  client/src/components/common/Like/Like.module.scss
  client/src/components/common/Like/index.tsx
  client/src/components/common/PageTitle/PageTitle.module.scss
  client/src/components/common/Paging/Paging.css
  client/src/components/common/Paging/index.tsx
  client/src/components/layout/Header/index.tsx
  client/src/components/road/CrsDesc/CrsDesc.module.scss
  client/src/components/road/CrsDesc/index.tsx
  client/src/components/road/crsInfo/CrsInfo.module.scss
  client/src/components/road/crsInfo/index.tsx
  client/src/components/roads/Filter/Filter.module.scss
  client/src/components/roads/Filter/index.tsx
  client/src/components/roads/Sort/Sort.module.scss
  client/src/components/roads/Sort/index.tsx
  client/src/components/signup/SecondSignupForm/index.tsx
  client/src/hooks/useOnClickOutside.ts
  client/src/routes/Road/Road.module.scss
  client/src/routes/Road/index.tsx
  client/src/routes/Roads/Roads.module.scss
  client/src/routes/Roads/index.tsx
  client/yarn.lock
Labels: feat✨, frontend

#45 feat: user_api & change pk type long -> integer
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/AuthDao.java
  src/main/java/com/joyride/ms/src/auth/AuthService.java
  src/main/java/com/joyride/ms/src/auth/PrincipalOAuth2UserService.java
  src/main/java/com/joyride/ms/src/auth/dto/PostSignupReq.java
  src/main/java/com/joyride/ms/src/jwt/JwtTokenProvider.java
  src/main/java/com/joyride/ms/src/jwt/filter/JwtAuthorizationFilter.java
  src/main/java/com/joyride/ms/src/user/UserController.java
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/UserProvider.java
  src/main/java/com/joyride/ms/src/user/UserService.java
  src/main/java/com/joyride/ms/src/user/dto/GetUserRes.java
  src/main/java/com/joyride/ms/src/user/model/User.java
Labels: backend, feat✨

#46 Feature/#38
  build.gradle
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/CourseInfo.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseListRes.java
Labels: backend, feat✨

#50 feat: 코스 리뷰 엔티티 생성
  src/main/java/com/joyride/ms/src/course/model/CourseReview.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseReviewRes.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewReq.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewRes.java
Labels: backend, feat✨

#53 refactor: api 키 숨기기(#51)
  build.gradle
  src/main/java/com/joyride/ms/src/config/SecurityConfig.java
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/CourseInfo.java
  src/main/java/com/joyride/ms/src/course/model/CourseReview.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseListRes.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseReviewRes.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewReq.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewRes.java
  src/main/resources/application.yml
Labels: bug🐞, backend, refactor💫

#54 Feature/#51
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/CourseReview.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseReviewRes.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewReq.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseReviewRes.java
Labels: backend, feat✨

#56 fix: 네트워크 미연결 시 이메일/닉네임 중복 확인 중 에러 발생시킴
  client/src/apis/authAPI.ts
  client/src/components/common/CheckBox/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupTerms/index.tsx
  client/src/index.tsx
  client/src/utils/getErrorMessage.ts
Labels: bug🐞, frontend

#57 feat: 유저 프로필 api 및 비밀번호 재설정 api
  build.gradle
  src/main/java/com/joyride/ms/src/auth/AuthController.java
  src/main/java/com/joyride/ms/src/auth/dto/PatchPasswordReq.java
  src/main/java/com/joyride/ms/src/s3/AwsS3Service.java
  src/main/java/com/joyride/ms/src/s3/config/AwsS3Config.java
  src/main/java/com/joyride/ms/src/s3/dto/PostProfileImgRes.java
  src/main/java/com/joyride/ms/src/user/UserController.java
  src/main/java/com/joyride/ms/src/user/UserDao.java
  src/main/java/com/joyride/ms/src/user/UserProvider.java
  src/main/java/com/joyride/ms/src/user/UserService.java
  src/main/java/com/joyride/ms/src/user/dto/PatchUserReq.java
  src/main/java/com/joyride/ms/src/user/dto/PatchUserRes.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
  src/main/resources/application.yml
Labels: backend, feat✨

#58 feat: 모임 리스트 카드 UI
  client/package.json
  client/src/apis/meetupAPI.ts
  client/src/components/common/Button/index.tsx
  client/src/components/common/Paging/Paging.css
  client/src/components/common/TextArea/TextArea.module.scss
  client/src/components/common/TextArea/index.tsx
  client/src/components/layout/Header/index.tsx
  client/src/components/login/SocialLogin/index.tsx
  client/src/components/login/SocialLoginButton/index.tsx
  client/src/components/meetups/MeetupCardContainer/MeetupCardContainer.module.scss
  client/src/components/meetups/MeetupCardContainer/index.tsx
  client/src/components/meetups/MeetupInfo/MeetupInfo.module.scss
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/meetups/MeetupItem/MeetupItem.module.scss
  client/src/components/meetups/MeetupItem/index.tsx
  client/src/components/meetups/MeetupList/MeetupList.module.scss
  client/src/components/meetups/MeetupList/index.tsx
  client/src/components/meetups/MeetupPath/MeetupPath.module.scss
  client/src/components/meetups/MeetupPath/index.tsx
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupCompleted/SignupCompleted.module.scss
  client/src/components/signup/SignupCompleted/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupForms/SignupForms.module.scss
  client/src/components/signup/SignupForms/index.tsx
  client/src/components/signup/SignupTerms/index.tsx
  client/src/hooks/useInput.ts
  client/src/routes/Login/Login.module.scss
  client/src/routes/Login/index.tsx
  client/src/routes/Meetups/Meetups.module.scss
  client/src/routes/Meetups/index.tsx
  client/src/routes/Signup/Signup.module.scss
  client/src/routes/Signup/index.tsx
  client/src/states/atoms.ts
  client/src/types/authentication.ts
  client/src/types/callback.ts
  client/src/types/course.ts
  client/src/types/meetup.ts
  client/src/utils/calculate.ts
  client/src/utils/getErrorMessage.ts
  client/src/utils/stringify.ts
  client/yarn.lock
Labels: feat✨, frontend

#59 feat: 모임 리스트 카드 UI 수정
  client/src/apis/meetupAPI.ts
  client/src/components/layout/Footer/index.tsx
  client/src/components/meetups/MeetupInfo/MeetupInfo.module.scss
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/meetups/MeetupItem/MeetupItem.module.scss
  client/src/components/meetups/MeetupItem/index.tsx
  client/src/components/meetups/MeetupList/index.tsx
  client/src/components/meetups/MeetupPath/MeetupPath.module.scss
  client/src/components/meetups/MeetupPath/index.tsx
  client/src/components/signup/SignupCompleted/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupForms/index.tsx
  client/src/components/signup/SignupTermsForm/SignupTermsForm.module.scss
  client/src/components/signup/SignupTermsForm/index.tsx
  client/src/components/signup/SignupTermsForm/terms.ts
  client/src/types/callback.ts
  client/src/types/course.ts
  client/src/types/meetup.ts
  client/src/utils/calculate.ts
  client/src/utils/constants.ts
Labels: refactor💫, feat✨, frontend

#60 chore: 이름 변경, type 추가
  client/src/App.tsx
  client/src/apis/meetupAPI.ts
  client/src/components/common/AuthRoute/index.tsx
  client/src/components/common/PublicRoute/index.tsx
  client/src/components/common/Toast/index.tsx
  client/src/components/layout/Header/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/meetups/MeetupItem/index.tsx
  client/src/components/meetups/MeetupPath/index.tsx
  client/src/components/meetups/MeetupRoute/MeetupRoute.module.scss
  client/src/components/meetups/MeetupRoute/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupTermsForm/index.tsx
  client/src/routes/Signup/index.tsx
  client/src/states/auth.ts
  client/src/states/common.ts
  client/src/states/selectors.ts
  client/src/types/callback.ts
  client/src/types/common.ts
  client/src/types/course.ts
  client/src/types/meetup.ts
  client/src/utils/constants.ts
  client/src/utils/stringify.ts
Labels: chore

#67 feat: 모임 필터 UI/상태 관리
  README.md
  client/src/apis/meetupAPI.ts
  client/src/components/common/AuthFormInput/index.tsx
  client/src/components/common/Button/Button.module.scss
  client/src/components/common/Button/index.tsx
  client/src/components/common/Container/Container.module.scss
  client/src/components/common/ErrorMessage/index.tsx
  client/src/components/common/OptionChip/OptionChip.module.scss
  client/src/components/common/OptionChip/index.tsx
  client/src/components/common/PageTitle/index.tsx
  client/src/components/common/PlusMinusButton/PlusMinusButton.module.scss
  client/src/components/common/PlusMinusButton/index.tsx
  client/src/components/common/SelectButton/index.tsx
  client/src/components/common/SelectList/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/meetups/MeetupFilterBoard/MeetupFilterBoard.module.scss
  client/src/components/meetups/MeetupFilterBoard/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/MeetupFilterBoardOptions.module.scss
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/components/meetups/MeetupFilterChoices/MeetupFilterChoices.module.scss
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/components/meetups/MeetupFilterToggleButton/MeetupFilterToggleButton.module.scss
  client/src/components/meetups/MeetupFilterToggleButton/index.tsx
  client/src/components/meetups/MeetupInfo/MeetupInfo.module.scss
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/meetups/MeetupItem/MeetupItem.module.scss
  client/src/components/signup/SignupBasicForm/index.tsx
  client/src/components/signup/SignupCompleted/index.tsx
  client/src/components/signup/SignupDetailForm/index.tsx
  client/src/components/signup/SignupTermsForm/index.tsx
  client/src/hooks/useClientFilter.ts
  client/src/hooks/useToggle.ts
  client/src/routes/Meetups/Meetups.module.scss
  client/src/routes/Meetups/index.tsx
  client/src/routes/Road/index.tsx
  client/src/routes/Signup/index.tsx
  client/src/states/auth.ts
  client/src/states/meetup.ts
  client/src/styles/base.scss
  client/src/styles/mixins.scss
  client/src/styles/variables.scss
  client/src/types/auth.ts
  client/src/types/authentication.ts
  client/src/types/callback.ts
  client/src/types/common.ts
  client/src/types/meetup.ts
  client/src/utils/constants.ts
  client/src/utils/filter.ts
  client/src/utils/stringify.ts
Labels: feat✨, frontend

#63 feat: 리뷰조회 api(#61)
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseReviewRes.java
Labels: backend, feat✨

#68 feat: 코스 정렬 컴포넌트 수정 및 페이지네이션 컴포넌트 추가
  client/package.json
  client/src/components/common/Paging/Paging.css
  client/src/components/common/Paging/Paging.module.scss
  client/src/components/common/Paging/index.tsx
  client/src/components/roads/Filter/Filter.module.scss
  client/src/components/roads/Filter/index.tsx
  client/src/components/roads/Sort/index.tsx
  client/src/components/roads/SortBox/SortBox.module.scss
  client/src/components/roads/SortBox/index.tsx
  client/src/components/roads/SortItem/SortItem.module.scss
  client/src/components/roads/SortItem/index.tsx
  client/src/routes/Roads/index.tsx
  client/src/states/common.ts
  client/src/types/course.ts
  client/src/utils/stringify.ts
  client/yarn.lock
Labels: feat✨, frontend

#69 feat: 모임 최종 필터 초기화 버튼, refactor: OptionChip
  client/src/components/common/OptionChip/index.tsx
  client/src/components/meetups/MeetupFilterBoard/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/hooks/useClientFilter.ts
  client/src/types/common.ts
  client/src/types/meetup.ts
  client/src/utils/filter.ts
Labels: refactor💫, feat✨, frontend

#75 feat: 모임 리스트 정렬
  client/src/components/common/AuthRoute/index.tsx
  client/src/components/common/ContentToggleButton/ContentToggleButton.module.scss
  client/src/components/common/ContentToggleButton/index.tsx
  client/src/components/common/OptionChip/index.tsx
  client/src/components/common/PublicRoute/index.tsx
  client/src/components/meetups/MeetupFilterBoard/index.tsx
  client/src/components/meetups/MeetupFilterBoardOptions/index.tsx
  client/src/components/meetups/MeetupFilterChoices/index.tsx
  client/src/components/meetups/MeetupInfo/index.tsx
  client/src/components/meetups/OrderItem/OrderItem.module.scss
  client/src/components/meetups/OrderItem/index.tsx
  client/src/components/meetups/OrderList/OrderList.module.scss
  client/src/components/meetups/OrderList/index.tsx
  client/src/hooks/useClientFilter.ts
  client/src/routes/Meetups/index.tsx
  client/src/states/meetup.ts
  client/src/types/common.ts
  client/src/types/meetup.ts
  client/src/utils/constants.ts
  client/src/utils/order.ts
Labels: feat✨, frontend

#71 Feature/#66
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseLikeRes.java
  src/main/java/com/joyride/ms/src/course/model/PostCourseLikeRes.java
Labels: backend, feat✨

#73 Feature/#70
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/DeleteCourseLikeRes.java
  src/main/java/com/joyride/ms/src/course/model/DeleteCourseReviewRes.java
  src/main/java/com/joyride/ms/util/BaseResponseStatus.java
Labels: backend, feat✨

#83 Feature/코스 디테일 api 수정#82
  src/main/java/com/joyride/ms/src/course/CallApi.java
  src/main/java/com/joyride/ms/src/course/CourseController.java
  src/main/java/com/joyride/ms/src/course/CourseDao.java
  src/main/java/com/joyride/ms/src/course/CourseProvider.java
  src/main/java/com/joyride/ms/src/course/CourseService.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseListRes.java
  src/main/java/com/joyride/ms/src/course/model/GetCourseRes.java
Labels: backend, refactor💫, feat✨
